import { Abril_Fatface, Inter } from "next/font/google";
import localFont from "next/font/local";
//.import LayoutWrapper from "./LayoutWrapper";
//import Footer from "./components/Footer";
import Header from "./components/Header";
import LoadingWrapper from "./components/LoadingWrapper";
import ThemeProvider from "./components/ThemeProvider";
import "./globals.css";
// Define your custom Softype font
const softype = localFont({
  src: "../../public/fonts/softype-reg.woff2",
  variable: "--font-softype",
  display: "swap"
});

// Configure Google Font (Abril Fatface)
const abrilFatface = Abril_Fatface({
  subsets: ["latin"],
  variable: "--font-abrilfatface",
  weight: "400", // Abril Fatface only has one weight
  display: "swap"
});
// Configure Google Font (Inter)
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ["400", "500", "700"], // Add weights as needed
  display: "swap"
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning className={`${abrilFatface.variable} ${inter.variable}`}>
      {/* inter */}
      <body>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem disableTransitionOnChange>
          <LoadingWrapper>
            <Header />
            {children}
            {/* <Footer /> */}
          </LoadingWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
